baseURL = "https://www.vendure.io/"
languageCode = "en-us"
title = "Vendure E-commerce"
googleAnalytics = "UA-133911942-1"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableGitInfo = true
images = ["share-image.jpg"]
disableKinds = [
  "taxonomy",
  "taxonomyTerm"
]
[params]
    BookSection = "docs"
[permalinks]
    blog = "/blog/:year/:month/:slug/"
[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
